name: admin-ui-schedule
namespace: official
version: 0.0.1-3
author: Wazo Team
display_name: Schedule
min_wazo_version: 18.02
tags:
  - internal
homepage: https://github.com/wazo-pbx/wazo-admin-ui-schedule
