plugin_format_version: 2
name: admin-ui-schedule
namespace: official
version: 0.0.1-2
author: Wazo Team
display_name: Schedule
min_wazo_version: 18.01
tags:
  - internal
homepage: https://github.com/wazo-pbx/wazo-admin-ui-schedule
