name: admin-ui-schedule
namespace: official
version: 0.0.1
author: Wazo Team
display_name: Schedule
min_wazo_version: 17.17
tags:
  - beta
  - internal
homepage: https://github.com/wazo-pbx/wazo-admin-ui-schedule
